/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 109bf479aaa3d403f3677634cbe7c933)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	ALLOWED_ORIGINS: "https://rakyzu.my.id";
	SUPABASE_URL: string;
	SUPABASE_PUBLISHABLE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY">> {}
}
