/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ad32d0871488052b421f21374deec152)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	ALLOWED_ORIGINS: "https://rakyzu.my.id";
	SUPABASE_URL: string;
	SUPABASE_PUBLISHABLE_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	PLAY_EVENT_WEBHOOK_SECRET: string;
	COMMERCE_WEBHOOK_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY" | "SUPABASE_SERVICE_ROLE_KEY" | "PLAY_EVENT_WEBHOOK_SECRET" | "COMMERCE_WEBHOOK_SECRET">> {}
}
